### ISSUE TITLE
build works with idf 5.1.3 but doesn't work with idf 5.2.2 or idf 5.3.1 (latest stable)

### ISSUE THREAD

**Issue by greenaddress** [jocover/esp32_u2f#9]
Hi, I was trying the project (thanks for developing it!) and as per title I noticed that it didn't build with idf 5.3.1

I tried with 5.2.2 and it also didn't build.

With 5.1.3 it built correctly.

the error for both 5.3.1 and 5.2.2 was similar and in tinyusb:
```
esp32_u2f/managed_components/espressif__tinyusb/src/portable/espressif/esp32sx/dcd_esp32sx.c:48:27: error: 'USB_OUT_EP_NUM' undeclared here (not in a function)
   48 | #define EP_MAX            USB_OUT_EP_NUM
      |                           ^~~~~~~~~~~~~~
```

I didn't explore further for now
